apiVersion: v1
kind: Secret
metadata:
  name: paulhuayhua-api-secret
  namespace: paulhuayhua-api-ns
  labels:
    app: paulhuayhua-api
type: Opaque
data:
  username: c2E=
  password: UGFzc3dvcmQxIQ==