apiVersion: v1
kind: ConfigMap
metadata:
  name: paulhuayhua-api-config
  namespace: paulhuayhua-api-ns
  labels:
    app: paulhuayhua-api

data:
  APP_ENV: "produccion"
  APP_PORT: "8085"
  APP_VERSION: "1.0.0"